//! DingoDB three-prong store stress / integrity rig (not a product CLI).
//!
//! 1. **pump** — autogenerated puts until on-disk size ≥ target (default 1 GiB)
//! 2. **chaos** — offline random garbage writes into `.dingo` segment files
//! 3. **monitor** — latency + salvage/scrub diagnostics
//!
//! Orchestrator: **run** = pump → baseline monitor → chaos → post-chaos monitor.
//! Scale ladder: pass at 1 GiB, then 10 GiB, then larger.

mod chaos;
mod manifest;
mod monitor;
mod pump;
mod size;

use chaos::{run_chaos, ChaosConfig};
use clap::{Parser, Subcommand};
use manifest::manifest_path_for_store;
use monitor::{evaluate_run, run_monitor, MonitorConfig};
use pump::{ensure_parent, parse_durability, run_pump, PumpConfig};
use serde_json::json;
use size::{format_bytes, parse_size};
use std::path::PathBuf;
use std::process::ExitCode;
use std::time::{SystemTime, UNIX_EPOCH};

const ABOUT: &str = "Three-prong DingoDB store stress rig: pump · chaos · monitor";

#[derive(Parser)]
#[command(
    name = "dingo-testrig",
    about = ABOUT,
    long_about = "Non-product harness for scale + damage campaigns.\n\n\
        Prong 1 (pump): fill a store to a target on-disk size with synthetic keys.\n\
        Prong 2 (chaos): punch random garbage into segment files while closed.\n\
        Prong 3 (monitor): measure gets/puts, salvage holes, scrub findings.\n\n\
        Suggested ladder: --target-bytes 1G, then 10G, then larger.\n\
        Numbers are diagnostic only (see doc/BENCHMARK_DISCLOSURE.md)."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Prong 1: pump autogenerated data until on-disk size ≥ target.
    Pump {
        /// Store directory (created if missing).
        #[arg(long, short = 's')]
        store: PathBuf,
        /// Target on-disk size (e.g. 1G, 10G, 256M). Default 1G.
        #[arg(long, default_value = "1G")]
        target_bytes: String,
        /// Synthetic payload size in bytes.
        #[arg(long, default_value_t = 4096)]
        payload_size: usize,
        /// Durability: memory | buffered | durable.
        #[arg(long, default_value = "buffered")]
        durability: String,
        /// Soft seal threshold for segment rotation.
        #[arg(long, default_value = "64M")]
        seal_threshold: String,
        /// RNG seed for payload fill (0 = from clock).
        #[arg(long, default_value_t = 0)]
        seed: u64,
        /// Key prefix (decimal index appended).
        #[arg(long, default_value = "load/")]
        key_prefix: String,
        /// Manifest path (default: sibling testrig-manifest.v1.json).
        #[arg(long)]
        manifest: Option<PathBuf>,
        /// Machine-readable JSON on stdout.
        #[arg(long)]
        json_out: bool,
    },
    /// Prong 2: write garbage at random offsets in segment files (store must be closed).
    Chaos {
        /// Store directory.
        #[arg(long, short = 's')]
        store: PathBuf,
        /// Number of random punches.
        #[arg(long, default_value_t = 16)]
        hits: u32,
        /// Bytes of garbage per punch.
        #[arg(long, default_value_t = 64)]
        bytes_per_hit: usize,
        /// RNG seed (0 = from clock).
        #[arg(long, default_value_t = 0)]
        seed: u64,
        /// Protect this many leading bytes of each file (unless --brutal).
        #[arg(long, default_value_t = 4096)]
        protect_head: u64,
        /// Protect this many trailing bytes (unless --brutal).
        #[arg(long, default_value_t = 64)]
        protect_tail: u64,
        /// Allow punching segment headers / tails.
        #[arg(long)]
        brutal: bool,
        #[arg(long)]
        json_out: bool,
    },
    /// Prong 3: performance + integrity sample.
    Monitor {
        /// Store directory.
        #[arg(long, short = 's')]
        store: PathBuf,
        /// Optional workload manifest from pump.
        #[arg(long)]
        manifest: Option<PathBuf>,
        /// How many keys to sample for get latency.
        #[arg(long, default_value_t = 64)]
        sample_keys: usize,
        /// Optional buffered put microbench count (0 = skip).
        #[arg(long, default_value_t = 32)]
        put_samples: usize,
        /// Label for this sample (baseline | post-chaos | …).
        #[arg(long, default_value = "adhoc")]
        phase: String,
        /// Skip writer-path scrub/puts (inspect + salvage only).
        #[arg(long)]
        inspect_only: bool,
        #[arg(long)]
        json_out: bool,
    },
    /// Full campaign: pump → baseline monitor → chaos → post-chaos monitor.
    Run {
        /// Work directory (store created as `<work>/store`).
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Target on-disk size (default 1G). Use 8M/32M for smoke.
        #[arg(long, default_value = "1G")]
        target_bytes: String,
        #[arg(long, default_value_t = 4096)]
        payload_size: usize,
        #[arg(long, default_value = "buffered")]
        durability: String,
        #[arg(long, default_value = "64M")]
        seal_threshold: String,
        #[arg(long, default_value_t = 16)]
        chaos_hits: u32,
        #[arg(long, default_value_t = 64)]
        chaos_bytes: usize,
        #[arg(long, default_value_t = 0)]
        seed: u64,
        #[arg(long, default_value_t = 64)]
        sample_keys: usize,
        /// Allow chaos into headers.
        #[arg(long)]
        brutal: bool,
        #[arg(long)]
        json_out: bool,
    },
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    let result = match cli.command {
        Command::Pump {
            store,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            seed,
            key_prefix,
            manifest,
            json_out,
        } => cmd_pump(
            store,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            seed,
            key_prefix,
            manifest,
            json_out,
        ),
        Command::Chaos {
            store,
            hits,
            bytes_per_hit,
            seed,
            protect_head,
            protect_tail,
            brutal,
            json_out,
        } => cmd_chaos(
            store,
            hits,
            bytes_per_hit,
            seed,
            protect_head,
            protect_tail,
            brutal,
            json_out,
        ),
        Command::Monitor {
            store,
            manifest,
            sample_keys,
            put_samples,
            phase,
            inspect_only,
            json_out,
        } => cmd_monitor(
            store,
            manifest,
            sample_keys,
            put_samples,
            phase,
            inspect_only,
            json_out,
        ),
        Command::Run {
            work,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            chaos_hits,
            chaos_bytes,
            seed,
            sample_keys,
            brutal,
            json_out,
        } => cmd_run(
            work,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            chaos_hits,
            chaos_bytes,
            seed,
            sample_keys,
            brutal,
            json_out,
        ),
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn resolve_seed(seed: u64) -> u64 {
    if seed != 0 {
        return seed;
    }
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0xD160_B17)
}

fn cmd_pump(
    store: PathBuf,
    target_bytes: String,
    payload_size: usize,
    durability: String,
    seal_threshold: String,
    seed: u64,
    key_prefix: String,
    manifest: Option<PathBuf>,
    json_out: bool,
) -> Result<(), String> {
    ensure_parent(&store).map_err(|e| format!("create parent: {e}"))?;
    let target = parse_size(&target_bytes)?;
    let seal = parse_size(&seal_threshold)?;
    let seed = resolve_seed(seed);
    let durability = parse_durability(&durability)?;
    let manifest_path = manifest.unwrap_or_else(|| manifest_path_for_store(&store));
    run_pump(&PumpConfig {
        store,
        target_bytes: target,
        payload_size,
        durability,
        seal_threshold: seal,
        seed,
        key_prefix,
        manifest_path,
        json_out,
    })
    .map(|_| ())
}

fn cmd_chaos(
    store: PathBuf,
    hits: u32,
    bytes_per_hit: usize,
    seed: u64,
    protect_head: u64,
    protect_tail: u64,
    brutal: bool,
    json_out: bool,
) -> Result<(), String> {
    let seed = resolve_seed(seed);
    run_chaos(&ChaosConfig {
        store,
        hits,
        bytes_per_hit,
        seed,
        protect_head,
        protect_tail,
        brutal,
        json_out,
    })
    .map(|_| ())
}

fn cmd_monitor(
    store: PathBuf,
    manifest: Option<PathBuf>,
    sample_keys: usize,
    put_samples: usize,
    phase: String,
    inspect_only: bool,
    json_out: bool,
) -> Result<(), String> {
    let r = run_monitor(&MonitorConfig {
        store,
        manifest_path: manifest,
        sample_keys,
        put_samples,
        phase,
        json_out,
        inspect_only,
    })?;
    if r.ok {
        Ok(())
    } else {
        Err(format!("monitor phase `{}` failed", r.phase))
    }
}

fn cmd_run(
    work: PathBuf,
    target_bytes: String,
    payload_size: usize,
    durability: String,
    seal_threshold: String,
    chaos_hits: u32,
    chaos_bytes: usize,
    seed: u64,
    sample_keys: usize,
    brutal: bool,
    json_out: bool,
) -> Result<(), String> {
    std::fs::create_dir_all(&work).map_err(|e| format!("create work dir: {e}"))?;
    let store = work.join("store");
    let manifest_path = work.join(manifest::MANIFEST_FILE);
    let target = parse_size(&target_bytes)?;
    let seal = parse_size(&seal_threshold)?;
    let seed = resolve_seed(seed);
    let durability = parse_durability(&durability)?;

    if !json_out {
        println!(
            "=== testrig run ===\nwork={}\nstore={}\ntarget={}\npayload={} durability={:?} seed={seed}",
            work.display(),
            store.display(),
            format_bytes(target),
            payload_size,
            durability
        );
        println!("\n--- prong 1: pump ---");
    }

    let pump_manifest = run_pump(&PumpConfig {
        store: store.clone(),
        target_bytes: target,
        payload_size,
        durability,
        seal_threshold: seal,
        seed,
        key_prefix: "load/".into(),
        manifest_path: manifest_path.clone(),
        json_out: false, // orchestrator owns final JSON
    })?;

    if !json_out {
        println!("\n--- prong 3a: baseline monitor ---");
    }
    let baseline = run_monitor(&MonitorConfig {
        store: store.clone(),
        manifest_path: Some(manifest_path.clone()),
        sample_keys,
        put_samples: 16,
        phase: "baseline".into(),
        json_out: false,
        inspect_only: false,
    })?;

    if !json_out {
        println!("\n--- prong 2: chaos ---");
    }
    // Store must be closed — monitors already dropped their handles.
    let chaos = run_chaos(&ChaosConfig {
        store: store.clone(),
        hits: chaos_hits,
        bytes_per_hit: chaos_bytes,
        seed: seed ^ 0xC4A0_5,
        protect_head: 4096,
        protect_tail: 64,
        brutal,
        json_out: false,
    })?;

    if !json_out {
        println!("\n--- prong 3b: post-chaos monitor ---");
    }
    let post = run_monitor(&MonitorConfig {
        store: store.clone(),
        manifest_path: Some(manifest_path.clone()),
        sample_keys,
        // After chaos, avoid writer puts that might seal over damage mid-bench.
        put_samples: 0,
        phase: "post-chaos".into(),
        json_out: false,
        inspect_only: true,
    })?;

    let (pass, reasons) = evaluate_run(&baseline, chaos.hits_applied, &post);

    let summary = json!({
        "prong": "run",
        "ok": pass,
        "work": work.display().to_string(),
        "store": store.display().to_string(),
        "target_bytes": target,
        "bytes_on_disk": pump_manifest.bytes_on_disk,
        "keys_written": pump_manifest.keys_written,
        "pump_ops_per_sec": pump_manifest.pump_ops_per_sec,
        "pump_mb_per_sec": pump_manifest.pump_mb_per_sec,
        "chaos_hits": chaos.hits_applied,
        "baseline": baseline.report,
        "post_chaos": post.report,
        "reasons": reasons,
        "ladder_hint": "If ok at 1G, re-run with --target-bytes 10G (then larger).",
        "disclosure": "Diagnostic only — not a published SLO (doc/BENCHMARK_DISCLOSURE.md).",
    });

    let summary_path = work.join("testrig-summary.v1.json");
    std::fs::write(
        &summary_path,
        serde_json::to_vec_pretty(&summary).unwrap(),
    )
    .map_err(|e| format!("write summary: {e}"))?;

    if json_out {
        println!("{}", serde_json::to_string_pretty(&summary).unwrap());
    } else {
        println!("\n=== result: {} ===", if pass { "PASS" } else { "FAIL" });
        for r in &reasons {
            println!("  - {r}");
        }
        println!("summary: {}", summary_path.display());
        println!(
            "ladder: pass here, then retry with --target-bytes 10G (then more)"
        );
    }

    if pass {
        Ok(())
    } else {
        Err("testrig run failed (see reasons above)".into())
    }
}
