//! Prong 1 — autogenerated data pump targeting a storage footprint.

use crate::manifest::{write_manifest, WorkloadManifest};
use crate::size::{dir_size_bytes, format_bytes};
use dingo_store::{DurabilityMode, Store};
use serde_json::json;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::time::Instant;

#[derive(Debug, Clone)]
pub struct PumpConfig {
    pub store: PathBuf,
    pub target_bytes: u64,
    pub payload_size: usize,
    pub durability: DurabilityMode,
    pub seal_threshold: u64,
    pub seed: u64,
    pub key_prefix: String,
    pub manifest_path: PathBuf,
    pub json_out: bool,
}

pub fn run_pump(cfg: &PumpConfig) -> Result<WorkloadManifest, String> {
    if cfg.target_bytes == 0 {
        return Err("target-bytes must be > 0".into());
    }
    if cfg.payload_size == 0 {
        return Err("payload-size must be > 0".into());
    }

    let mut store = Store::open(&cfg.store).map_err(|e| format!("open/create store: {e}"))?;
    store.set_seal_threshold(cfg.seal_threshold);

    // Deterministic-looking payload body (not crypto). Pattern helps spot garbage later.
    let mut payload = vec![0u8; cfg.payload_size];
    fill_payload(&mut payload, cfg.seed);

    let t0 = Instant::now();
    let mut keys_written = 0u64;
    let mut last_report = Instant::now();

    // Size check every N puts — dir walk is expensive at GB scale.
    let size_check_every = size_check_interval(cfg.target_bytes, cfg.payload_size);

    loop {
        let key = format!("{}{:020}", cfg.key_prefix, keys_written);
        store
            .put(&key, &payload, cfg.durability)
            .map_err(|e| format!("put {key}: {e}"))?;
        keys_written += 1;

        if keys_written % size_check_every == 0 || keys_written == 1 {
            let on_disk = dir_size_bytes(&cfg.store).map_err(|e| format!("dir size: {e}"))?;
            if on_disk >= cfg.target_bytes {
                break;
            }
            if !cfg.json_out && last_report.elapsed().as_secs() >= 2 {
                let elapsed = t0.elapsed().as_secs_f64().max(1e-9);
                eprintln!(
                    "pump: keys={keys_written} disk={} / {} ({:.1}%) {:.1} ops/s {:.2} MB/s",
                    format_bytes(on_disk),
                    format_bytes(cfg.target_bytes),
                    100.0 * on_disk as f64 / cfg.target_bytes as f64,
                    keys_written as f64 / elapsed,
                    (on_disk as f64 / (1024.0 * 1024.0)) / elapsed
                );
                last_report = Instant::now();
            }
        }

        // Safety: if payload is tiny and metadata dominates oddly, still stop.
        if keys_written >= 50_000_000 {
            return Err("pump abort: 50M keys without reaching target (raise payload-size?)".into());
        }
    }

    // Seal active so chaos has sealed segment files to punch.
    let _ = store.seal_active();
    drop(store);

    let elapsed = t0.elapsed();
    let bytes_on_disk = dir_size_bytes(&cfg.store).map_err(|e| format!("dir size: {e}"))?;
    let secs = elapsed.as_secs_f64().max(1e-9);
    let ops_per_sec = keys_written as f64 / secs;
    let mb_per_sec = (bytes_on_disk as f64 / (1024.0 * 1024.0)) / secs;

    let manifest = WorkloadManifest {
        format_version: 1,
        store_path: cfg.store.display().to_string(),
        target_bytes: cfg.target_bytes,
        payload_size: cfg.payload_size,
        durability: durability_label(cfg.durability).into(),
        keys_written,
        first_key: format!("{}{:020}", cfg.key_prefix, 0),
        last_key: format!("{}{:020}", cfg.key_prefix, keys_written.saturating_sub(1)),
        key_prefix: cfg.key_prefix.clone(),
        bytes_on_disk,
        pump_elapsed_ms: elapsed.as_millis() as u64,
        pump_ops_per_sec: ops_per_sec,
        pump_mb_per_sec: mb_per_sec,
        seed: cfg.seed,
    };

    write_manifest(&cfg.manifest_path, &manifest).map_err(|e| format!("write manifest: {e}"))?;

    let report = json!({
        "prong": "pump",
        "ok": bytes_on_disk >= cfg.target_bytes,
        "keys_written": keys_written,
        "bytes_on_disk": bytes_on_disk,
        "target_bytes": cfg.target_bytes,
        "payload_size": cfg.payload_size,
        "durability": durability_label(cfg.durability),
        "elapsed_ms": manifest.pump_elapsed_ms,
        "ops_per_sec": ops_per_sec,
        "mb_per_sec": mb_per_sec,
        // Honest concurrency disclosure (doc/BENCHMARK_DISCLOSURE.md, DEF-096).
        // Pump is a single exclusive writer over one active segment today.
        "concurrency": 1,
        "writer_model": "single_active_segment",
        "manifest": cfg.manifest_path.display().to_string(),
        "store": cfg.store.display().to_string(),
    });

    if cfg.json_out {
        println!("{}", serde_json::to_string_pretty(&report).unwrap());
    } else {
        println!(
            "pump done: keys={keys_written} disk={} (target {}) in {:.2}s — {:.1} ops/s, {:.2} MB/s",
            format_bytes(bytes_on_disk),
            format_bytes(cfg.target_bytes),
            secs,
            ops_per_sec,
            mb_per_sec
        );
        println!("manifest: {}", cfg.manifest_path.display());
    }

    if bytes_on_disk < cfg.target_bytes {
        return Err(format!(
            "pump under target: {} < {}",
            format_bytes(bytes_on_disk),
            format_bytes(cfg.target_bytes)
        ));
    }
    Ok(manifest)
}

fn fill_payload(buf: &mut [u8], seed: u64) {
    // Simple LCG fill — fast and reproducible for a given seed.
    let mut state = seed ^ 0xD1_160_B17_u64;
    for (i, b) in buf.iter_mut().enumerate() {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1);
        *b = ((state >> 33) as u8).wrapping_add((i & 0xff) as u8);
    }
    // Magic prefix so corrupted regions are obvious in hex dumps.
    let magic = b"DINGO-TESTRIG-PAYLOAD-v1\n";
    let n = magic.len().min(buf.len());
    buf[..n].copy_from_slice(&magic[..n]);
}

fn size_check_interval(target: u64, payload: usize) -> u64 {
    // Aim for ~64 size checks across the run, but not more often than every 32 puts.
    let approx_keys = (target / payload.max(1) as u64).max(1);
    (approx_keys / 64).clamp(32, 4096)
}

pub fn durability_label(d: DurabilityMode) -> &'static str {
    match d {
        DurabilityMode::Memory => "memory",
        DurabilityMode::Buffered => "buffered",
        DurabilityMode::Durable => "durable",
    }
}

pub fn parse_durability(s: &str) -> Result<DurabilityMode, String> {
    match s.to_ascii_lowercase().as_str() {
        "memory" | "mem" => Ok(DurabilityMode::Memory),
        "buffered" | "buffer" | "buf" => Ok(DurabilityMode::Buffered),
        "durable" | "sync" | "fsync" => Ok(DurabilityMode::Durable),
        other => Err(format!(
            "unknown durability `{other}` (memory|buffered|durable)"
        )),
    }
}

/// Ensure parent dirs exist for store path.
pub fn ensure_parent(store: &Path) -> io::Result<()> {
    if let Some(p) = store.parent() {
        fs::create_dir_all(p)?;
    }
    Ok(())
}
